# Generated by Django 6.0.6 on 2026-06-10 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Curriculum Enviado'), ('ENTREVISTA', 'En proceso de entrevista'), ('ACEPTADA', '¡Contratado!'), ('RECHAZADA', 'Descartado')], default='ENVIADA', max_length=15)),
                ('fecha_aplicacion', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='eventos.evento')),
            ],
        ),
    ]
